ellison/simplified steps and optimization experience
vangie/poetry pull request #3
Opened 2019-12-26 05:55 UTC by coco-super

2019-12-26 07:02 UTC, vangie commented
@coco-super 建议写一个 Makefile 把训练模型的代码迁移到 Makefile 里去。

2019-12-26 07:08 UTC, vangie requested changes

2019-12-26 07:08 UTC, vangie commented on README.md
> +基本上所有的 FaaS 平台为了减少平台的冷启动，都会设置代码包限制，函数计算也不例外。由于 python TensorFlow 依赖库和训练的模型的文件有数百兆，即使压缩也远超了函数计算 50M 代码包大小的限制。对于这类超大体积的文件，函数计算命令行 Fun 工具原生支持了这种大依赖部署（3.2.0 版本以上），只需根据向导不需额外操作。
只需根据向导不需额外操作。 =》 按照向导的提示操作即可。

2019-12-26 07:08 UTC, vangie commented on README.md
> +执行 `fun install` 安装 FunFile 中声明的 tensorflow 依赖。由于训练模型的脚本比较费时，所以提前将训练好的模型存放在 model 目录中。
由于训练模型的脚本比较费时，所以训练好的模型已经提前存放在 model 目录中。如果您想重新训练模型，执行 `make train` 即可。

2019-12-26 07:08 UTC, vangie commented on README.md
> +### 3. 运行本地函数
运行本地函数 => 本地运行函数

2019-12-26 07:08 UTC, vangie commented on README.md
> +```bash
该方式是操作繁琐而且需要预先准备一台 VPC 内的 ECS 主机，所以不推荐。

2019-12-26 11:33 UTC, coco-super commented on README.md
> +执行 `fun install` 安装 FunFile 中声明的 tensorflow 依赖。由于训练模型的脚本比较费时，所以提前将训练好的模型存放在 model 目录中。
done

2019-12-26 11:34 UTC, coco-super commented on README.md
> +基本上所有的 FaaS 平台为了减少平台的冷启动，都会设置代码包限制，函数计算也不例外。由于 python TensorFlow 依赖库和训练的模型的文件有数百兆，即使压缩也远超了函数计算 50M 代码包大小的限制。对于这类超大体积的文件，函数计算命令行 Fun 工具原生支持了这种大依赖部署（3.2.0 版本以上），只需根据向导不需额外操作。
done

2019-12-26 11:34 UTC, coco-super commented on README.md
> +```bash
> @coco-super 建议写一个 Makefile 把训练模型的代码迁移到 Makefile 里去。

done

2019-12-26 11:35 UTC, coco-super commented on README.md
> +```bash
> 该方式是操作繁琐而且需要预先准备一台 VPC 内的 ECS 主机，所以不推荐。

ecs 我删掉了？确定一下要在 readme 中说明吗？

2019-12-26 11:35 UTC, coco-super commented on README.md
> +### 3. 运行本地函数
done

2019-12-27 02:26 UTC, vangie approved these changes

2019-12-27 02:28 UTC, merged